export function getSubdomain(host?: string): string | null {
  // Для серверной части используем переданный host
  if (host) {
    const parts = host.split(".");
    if (parts.length < 3) return null;
    const subdomain = parts[0];
    return subdomain === "www" ? null : subdomain;
  }

  // Для клиентской части используем window.location
  if (typeof window === "undefined") {
    return null;
  }

  const hostname = window.location.hostname;
  const parts = hostname.split(".");

  if (parts.length >= 3) {
    const subdomain = parts[0];
    return subdomain === "www" ? null : subdomain;
  }

  return null;
}

export function regionDisplay(region: string): string {
  const map: Record<string, string> = {
    moskva: "Москве",
    spb: "Санкт-Петербурге",
    rostov: "Ростове-на-Дону",
    ekaterinburg: "Екатеринбурге",
    krasnodar: "Краснодаре",
    makhachkala: "Махачкале",
    novosibirsk: "Новосибирске",
    nnovgorod: "Нижнем Новгороде",
    tyumen: "Тюмени",
    samara: "Самаре",
    kazan: "Казани",
    sochi: "Сочи",
    kaluga: "Калуге",
    grozny: "Грозном",
    ufa: "Уфе",
    voronezh: "Воронеже",
    chelyabinsk: "Челябинске",
    krasnoyarsk: "Красноярске",
    omsk: "Омске",
    volgograd: "Волгограде",
    orenburg: "Оренбурге",
    perm: "Перми",
    saratov: "Саратове",
    togliatti: "Тольятти",
    barnaul: "Барнауле",
    izhevsk: "Ижевске",
    khabarovsk: "Хабаровске",
    ulyanovsk: "Ульяновске",
    irkutsk: "Иркутске",
    vladivostok: "Владивостоке",
    yaroslavl: "Ярославле",
    stavropol: "Ставрополе",
    sevastopol: "Севастополе",
    nabchelny: "Набережных Челнах",
    tomsk: "Томске",
    balashikha: "Балашихе",
    kemerovo: "Кемерово",
    novokuznetsk: "Новокузнецке",
    ryazan: "Рязани",
    cheboksary: "Чебоксарах",
    kaliningrad: "Калининграде",
    penza: "Пензе",
    lipetsk: "Липецке",
    kirov: "Кирове",
    astrakhan: "Астрахани",
    tula: "Туле",
    ulanude: "Улан-Удэ",
    kursk: "Курске",
    surgut: "Сургуте",
    tver: "Твери",
    magnitogorsk: "Магнитогорске",
    yakutsk: "Якутске",
    bryansk: "Брянске",
    ivanovo: "Иванове",
    vladimir: "Владимире",
    chita: "Чите",
    belgorod: "Белгороде",
    podolsk: "Подольске",
    volzhsky: "Волжском",
    vologda: "Вологде",
    smolensk: "Смоленске",
    saransk: "Саранске",
    kurgan: "Кургане",
    cherepovets: "Череповце",
    arkhangelsk: "Архангельске",
    vladikavkaz: "Владикавказе",
    orel: "Орле",
    yoshkarola: "Йошкар-Оле",
    sterlitamak: "Стерлитамаке",
    kostroma: "Костроме",
    murmansk: "Мурманске",
    novorossiysk: "Новороссийске",
    tambov: "Тамбове",
    taganrog: "Таганроге",
    blagoveshchensk: "Благовещенске",
    vnovgorod: "Великом Новгороде",
    shakhty: "Шахтах",
    syktyvkar: "Сыктывкаре",
    pskov: "Пскове",
    orsk: "Орске",
    khantymansiysk: "Ханты-Мансийске",
    nazran: "Назрани",
    derbent: "Дербенте",
    nizhnevartovsk: "Нижневартовске",
    novyurengoy: "Новом Уренгое",
    gatchina: "Гатчине",
    kyzyl: "Кызыле",
    nalchik: "Нальчике",
    elista: "Элисте",
    magadan: "Магадане",
    pkamchatsky: "Петропавловске-Камчатском",
    domodedovo: "Домодедово",
    khimki: "Химках",
    mytishchi: "Мытищах",
    lyubertsy: "Люберцах",
    hasavyurt: "Хасавюрте",
    kaspiysk: "Каспийске",
    kizlyar: "Кизляре",
    default: "",
  };

  return map[region] || map["default"];
}

export function regionName(region: string): string {
  const map: Record<string, string> = {
    moskva: "Москва",
    spb: "Санкт-Петербург",
    rostov: "Ростов-на-Дону",
    ekaterinburg: "Екатеринбург",
    krasnodar: "Краснодар",
    makhachkala: "Махачкала",
    novosibirsk: "Новосибирск",
    nnovgorod: "Нижний Новгород",
    tyumen: "Тюмень",
    samara: "Самара",
    kazan: "Казань",
    sochi: "Сочи",
    kaluga: "Калуга",
    grozny: "Грозный",
    ufa: "Уфа",
    voronezh: "Воронеж",
    chelyabinsk: "Челябинск",
    krasnoyarsk: "Красноярск",
    omsk: "Омск",
    volgograd: "Волгоград",
    orenburg: "Оренбург",
    perm: "Пермь",
    saratov: "Саратов",
    togliatti: "Тольятти",
    barnaul: "Барнаул",
    izhevsk: "Ижевск",
    khabarovsk: "Хабаровск",
    ulyanovsk: "Ульяновск",
    irkutsk: "Иркутск",
    vladivostok: "Владивосток",
    yaroslavl: "Ярославль",
    stavropol: "Ставрополь",
    sevastopol: "Севастополь",
    nabchelny: "Набережные Челны",
    tomsk: "Томск",
    balashikha: "Балашиха",
    kemerovo: "Кемерово",
    novokuznetsk: "Новокузнецк",
    ryazan: "Рязань",
    cheboksary: "Чебоксары",
    kaliningrad: "Калининград",
    penza: "Пенза",
    lipetsk: "Липецк",
    kirov: "Киров",
    astrakhan: "Астрахань",
    tula: "Тула",
    ulanude: "Улан-Удэ",
    kursk: "Курск",
    surgut: "Сургут",
    tver: "Тверь",
    magnitogorsk: "Магнитогорск",
    yakutsk: "Якутск",
    bryansk: "Брянск",
    ivanovo: "Иваново",
    vladimir: "Владимир",
    chita: "Чита",
    belgorod: "Белгород",
    podolsk: "Подольск",
    volzhsky: "Волжский",
    vologda: "Вологда",
    smolensk: "Смоленск",
    saransk: "Саранск",
    kurgan: "Курган",
    cherepovets: "Череповец",
    arkhangelsk: "Архангельск",
    vladikavkaz: "Владикавказ",
    orel: "Орёл",
    yoshkarola: "Йошкар-Ола",
    sterlitamak: "Стерлитамак",
    kostroma: "Кострома",
    murmansk: "Мурманск",
    novorossiysk: "Новороссийск",
    tambov: "Тамбов",
    taganrog: "Таганрог",
    blagoveshchensk: "Благовещенск",
    vnovgorod: "Великий Новгород",
    shakhty: "Шахты",
    syktyvkar: "Сыктывкар",
    pskov: "Псков",
    orsk: "Орск",
    khantymansiysk: "Ханты-Мансийск",
    nazran: "Назрань",
    derbent: "Дербент",
    nizhnevartovsk: "Нижневартовск",
    novyurengoy: "Новый Уренгой",
    gatchina: "Гатчина",
    kyzyl: "Кызыл",
    nalchik: "Нальчик",
    elista: "Элиста",
    magadan: "Магадан",
    pkamchatsky: "Петропавловск-Камчатский",
    domodedovo: "Домодедово",
    khimki: "Химки",
    mytishchi: "Мытищи",
    lyubertsy: "Люберцы",
    hasavyurt: "Хасавюрт",
    kaspiysk: "Каспийск",
    kizlyar: "Кизляр",
    default: "Вся Россия",
  };

  return map[region] || "Выбрать регион";
}
